#' Add a new column for residues with PTMs and their positions in their native proteins.
#'
#' This function requires the add_seq_info function to be run first to add the column called 'sequence_modified'.
#' From this, and the columns called 'start' and 'end', this function uses this information to fill a new column with
#' residues with PTMs and their positions in their native proteins. There is the option to subtract 1 from both the start
#' and end columns because with some proteins the first residue, methionine, is removed after the protein is synthesised.
#' Therefore, some nomenclatures refer to the 2nd residue as the 1st, which is the case in the protein's mature state.
#'
#' @param df_with_sequences_modified A dataframe with a column name 'sequence_modified' generated by add_seq_info function.
#' @param subtract_1 Option to subtract 1 from the start and end columns. Defaults to FALSE.
#' @return The \code{df_with_annotated_seqs} with the new column 'PTMs_and_positions'.
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @importFrom utils data
#' @export

add_positions_of_PTMs_col <- function(df_with_sequences_modified, subtract_1 = FALSE){

  #Subtract 1 if specified from the start and end columns.

  if(subtract_1 == TRUE){

    df_with_sequences_modified <- df_with_sequences_modified %>%
      dplyr::mutate(start = .data$start - 1, end = .data$end - 1)

  }

  #Add new column to df

  PTM_position_drilldown_df <- df_with_sequences_modified %>%
    dplyr::rowwise() %>%
    dplyr::mutate(PTMs_and_positions = positions_of_PTMs_1_seq(.data$start, .data$end, .data$sequence_modified)) %>%
    dplyr::ungroup() %>%
    as.data.frame()

  return(PTM_position_drilldown_df)

}

#Helpers

positions_of_PTMs_1_seq <- function(start_position, end_position, sequence_with_PTMs){

  . <- NULL

  vector_start_to_end <- c(start_position:end_position)

  #Remove shorthand N and C terminal modifications. E.g. "Pro-".

  sequence_with_PTMs <- sequence_with_PTMs %>%
    stringr::str_remove(., "^.+?-") %>%
    stringr::str_remove(., "-.+$")

  #Separate all amino acids (with their shorthand PTMs)

  separated_residues <- stringr::str_split(sequence_with_PTMs, "(?<=.)(?=[A-Z])") %>%
    unlist()

  #Assign each residue a number and select only residues that have PTMs.

  df_with_PTMs_and_positions_on_histone <- data.frame(vector_start_to_end, separated_residues) %>%
    dplyr::filter(stringr::str_detect(separated_residues, "[A-Z].+"))

  #Get output. E.g. "K27cr, K36ac"

  shorthand_PTMs_and_positions <- stringr::str_replace(df_with_PTMs_and_positions_on_histone$separated_residues, "(?<=[A-Z])(?=[a-z])", as.character(df_with_PTMs_and_positions_on_histone$vector_start_to_end)) %>%
    unlist() %>%
    paste(., collapse = ", ")



}













