#' For a given string calculate the average number of that string per row, weighted by abundance or just count.
#'
#' It is recommended to use the merge_repeats function before this.
#'
#' @param df_with_annotated_seqs A dataframe with a column name 'sequence_modified' generated by add_seq_info function
#' @param PTMs_of_interest Shorthand form of PTMs, PTMs and residues or just residues.
#' @param weight_by_abundance A dataframe of all the longhand and corresponding shorthand names for PTMs.
#' @param abundance_colnames A vector of the abundance columns. If this is left blank all column names with 'abundance' in them will be used.
#' @param decimal_places How many decimal places the output should be given to.
#' @return A dataframe with the average number of the specified string per row, given by PTMs_of_interest.
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @importFrom utils data
#' @export

average_freq_of_PTM_per_seq <- function(df_with_annotated_seqs, PTMs_of_interest, weight_by_abundance = T, abundance_colnames, decimal_places = 3) {

if (missing(abundance_colnames) && weight_by_abundance == T) {


  abundance_colnames <- df_with_annotated_seqs %>%
    names(.) %>%
    data.frame() %>%
    dplyr::filter(stringr::str_detect(., "abundance"))

  abundance_colnames <- abundance_colnames[[1]]
}

output_df <- as.numeric()

if (weight_by_abundance == T) {

for (z in abundance_colnames) {

  vector_for_1_abundance <- as.numeric()

  for (i in PTMs_of_interest) {

    number_of_PTMs_vector <- df_with_annotated_seqs$sequence_modified %>%
      stringr::str_count(pattern = i)

    df_with_no_PTMs_per_seq <- dplyr::mutate(df_with_annotated_seqs, No_of_PTMs = number_of_PTMs_vector)

    sum_abundance_times_PTM_freq <- df_with_no_PTMs_per_seq %>%
      dplyr::mutate(abundance_times_PTM_freq = .[z]*.data$No_of_PTMs) %>% #Could replace this code in the future to make the code go faster.
      dplyr::summarise(sum(.data$abundance_times_PTM_freq, na.rm = TRUE))

    sum_abundance <- df_with_annotated_seqs %>%
      dplyr::summarise(sum(.[z], na.rm = TRUE))

    Average_no_of_PTMs <- (sum_abundance_times_PTM_freq/sum_abundance) %>%
      as.numeric()

    Average_no_of_PTMs <- signif(Average_no_of_PTMs, digits = decimal_places)

    vector_for_1_abundance <- append(vector_for_1_abundance, Average_no_of_PTMs)

    }

  output_df <- cbind(output_df, vector_for_1_abundance)

  }

colnames(output_df) <- abundance_colnames
rownames(output_df) <- PTMs_of_interest
output_df <- output_df[,order(colnames(output_df))] #Order column names alphabetically.

}

if (weight_by_abundance == F) {


for (i in PTMs_of_interest) {

    sum_of_number_of_PTMs <- df_with_annotated_seqs$sequence_modified %>%
      stringr::str_count(pattern = i) %>%
      sum(., na.rm = TRUE)

    total_number_of_seqs <- nrow(df_with_annotated_seqs)

    Average_no_of_PTMs <- (sum_of_number_of_PTMs/total_number_of_seqs) %>%
      as.numeric() %>%
      signif(., digits = decimal_places)

    output_df <- append(output_df, Average_no_of_PTMs)

  }
  output_df <- data.frame(output_df)
  colnames(output_df) <- "Average number of PTM per sequence by count"
  rownames(output_df) <- PTMs_of_interest

}



return(output_df)


}








