#' For a given string, usually a PTM, calculate the proportion of rows with that string
#'
#' It is recommended to use the merge_repeats function before this.
#'
#' @param df_with_annotated_seqs A dataframe with a column name 'sequence_modified' generated by add_seq_info function
#' @param PTMs_of_interest Shorthand form of PTMs, PTMs and residues or just residues.
#' @param weight_by_abundance A dataframe of all the longhand and corresponding shorthand names for PTMs.
#' @param abundance_colnames A vector of the abundance columns. If this is left blank all column names with 'abundance' in them will be used.
#' @param decimal_places How many decimal places the output should be given to.
#' @return A dataframe with the average number of the specified string per row, given by PTMs_of_interest.
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @importFrom utils data
#' @export

prop_of_rows_with_PTM <- function(df_with_annotated_seqs, PTMs_of_interest, weight_by_abundance = T, abundance_colnames, decimal_places = 3) {

  if (missing(abundance_colnames) && weight_by_abundance == T) {


    abundance_colnames <- df_with_annotated_seqs %>%
      names(.) %>%
      data.frame() %>%
      dplyr::filter(stringr::str_detect(., "abundance"))

    abundance_colnames <- abundance_colnames[[1]]
  }

  output_df <- as.numeric()

  if (weight_by_abundance == T) {

    for (z in abundance_colnames) {

      vector_for_1_abundance <- as.numeric()

      for (i in PTMs_of_interest) {

        is_PTM_present_vector <- df_with_annotated_seqs$sequence_modified %>%
          stringr::str_detect(pattern = i) %>%
          as.integer()

        df_with_binary_PTM_presence_col <- dplyr::mutate(df_with_annotated_seqs, PTM_presence = is_PTM_present_vector)

        sum_abundance_times_PTM_freq <- df_with_binary_PTM_presence_col %>%
          dplyr::mutate(abundance_times_PTM_freq = .[z]*.data$PTM_presence) %>% #Could replace this code in the future to make the code go faster.
          dplyr::summarise(sum(.data$abundance_times_PTM_freq, na.rm = TRUE))

        sum_abundance <- df_with_annotated_seqs %>%
          dplyr::summarise(sum(.[z], na.rm = TRUE))

        Average_no_of_PTMs <- (sum_abundance_times_PTM_freq/sum_abundance) %>%
          as.numeric()

        Average_no_of_PTMs <- signif(Average_no_of_PTMs, digits = decimal_places)

        vector_for_1_abundance <- append(vector_for_1_abundance, Average_no_of_PTMs)

      }

      output_df <- cbind(output_df, vector_for_1_abundance)

    }

    colnames(output_df) <- abundance_colnames
    rownames(output_df) <- PTMs_of_interest
    output_df <- output_df[,order(colnames(output_df))] #Order column names alphabetically.
  }

  if (weight_by_abundance == F) {


    for (i in PTMs_of_interest) {

      number_of_rows_with_PTM <- df_with_annotated_seqs$sequence_modified %>%
        stringr::str_detect(pattern = i) %>%
        as.integer() %>%
        sum(., na.rm = TRUE)

      total_number_of_seqs <- nrow(df_with_annotated_seqs)

      prop_of_seqs_with_PTM <- (number_of_rows_with_PTM/total_number_of_seqs) %>%
        as.numeric() %>%
        signif(., digits = decimal_places)

      output_df <- append(output_df, prop_of_seqs_with_PTM)

    }
    output_df <- data.frame(output_df)
    colnames(output_df) <- "Proportion of sequences with PTM"
    rownames(output_df) <- PTMs_of_interest

  }

  return(output_df)


}








?prop_of_rows_with_PTM
